# Generated by Django 4.2.14 on 2024-07-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbrepo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id_item_group', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'item_group',
                'managed': False,
            },
        ),
    ]
